### ISSUE TITLE
Selecting a MATLAB version

### ISSUE THREAD

**Issue by Krastanov** [mathworks/ci-configuration-examples#27]
Hello! Is there a way to select the MATLAB version to be used in the CI?

**Comment by acampbel** [comment]
Yes, the setup-matlab action has a `release` parameter that controls which release of MATLAB you will use. This looks something like

```
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
          release: R2022b
```


You can even run it across many versions. This looks something like this:
```
jobs:
  build:
    strategy:
      matrix:
        release: [R2022b, R2023a, R2023b]
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4     
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
          release: ${{matrix.release}}
```

Hope that helps! Please consult the documentation for more information
